### Login con admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}

### Login con username (hardcoded)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}
